import Head from 'next/head'
import Image from 'next/image'
import Home from '../components/home'
import Sidenav from '../components/sidenav'
import Navbar from './../components/navbar/index'

export default function App() {
    return (
        <>
            <Head>
                <title>OAU - Minimarts</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        
            <div className="w-full h-[100vh] bg-black relative">
                <Navbar/>
                <Sidenav/>
                <Home/>
            </div>

        </>
    )
}
